Class {
	#name : #ManifestBanques,
	#superclass : #PackageManifest,
	#category : #'TPE-POO4'
}

{ #category : #'code-critics' }
ManifestBanques class >> ruleRBGlobalVariablesUsageV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'TPE-POO4')) #'2020-07-02T23:15:01.523475+02:00') )
]

{ #category : #'code-critics' }
ManifestBanques class >> ruleRBImplementedNotSentRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'TPE-POO4')) #'2020-07-02T23:09:28.213475+02:00') )
]

{ #category : #'code-critics' }
ManifestBanques class >> ruleRBInconsistentMethodClassificationRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'TPE-POO4')) #'2020-07-02T23:15:46.235475+02:00') )
]

{ #category : #'code-critics' }
ManifestBanques class >> ruleRBNoClassCommentRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'TPE-POO4')) #'2020-07-02T23:03:32.145475+02:00') )
]

{ #category : #'code-critics' }
ManifestBanques class >> ruleRBReturnsBooleanAndOtherRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'TPE-POO4')) #'2020-07-02T23:15:20.116475+02:00') )
]

{ #category : #'code-critics' }
ManifestBanques class >> ruleRBUnaryAccessingMethodWithoutReturnRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'TPE-POO4')) #'2020-07-02T23:14:31.947475+02:00') )
]

{ #category : #'code-critics' }
ManifestBanques class >> ruleRBUnclassifiedMethodsRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'TPE-POO4')) #'2020-07-02T23:09:23.896475+02:00') )
]

{ #category : #'code-critics' }
ManifestBanques class >> ruleReNoNilAssignationInInitializeRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'TPE-POO4')) #'2020-07-02T23:15:42.370475+02:00') )
]

{ #category : #'code-critics' }
ManifestBanques class >> ruleRePackageManifestShouldBePackagedInManifestTagV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'TPE-POO4')) #'2020-07-02T23:03:27.962475+02:00') )
]

{ #category : #'as yet unclassified' }
ManifestBanques >> ruleGRIvarNeitherReadNorWrittenRuleV1FalsePositive [
	^ #(#(#(#RGClassDefinition #(#Banque)) #'2020-06-30T11:49:23.649238+01:00') )
]

{ #category : #'code-critics' }
ManifestBanques >> ruleRBUsesTrueRuleV1FalsePositive [
	^ #(#(#(#RGPackage #(#Banques)) #'2020-06-30T15:23:06.287903+01:00') )
]
